### ISSUE TITLE
[Bug report] Error highlights are unreadable under cursorline

### ISSUE THREAD

**Issue by arcnmx** [tinted-theming/tinted-vim#27] opened 2021-09-04 16:58 UTC
The issue described in #23 still exists since the PR seems to have been reverted. The foreground colour of error highlights makes the text nearly indistinguishable from the cursor line highlight bg colour.

![before](https://user-images.githubusercontent.com/3954671/116581835-50e6b080-a947-11eb-8ca1-cbca9bcedc8b.png)

**Comment by GordianDziwis** [comment] 2021-09-05 10:38
Does setting `:set termguicolors` help?

**Comment by arcnmx** [comment] 2021-09-07 12:44
That doesn't have any effect as far as I can tell.

**Comment by GordianDziwis** [comment] 2021-09-08 10:54
Can you give a minimal vimrc to reproduce?

**Comment by arcnmx** [comment] 2022-01-05 20:41
Oh, was this resolved? I'm currently [using a fork to resolve it](https://github.com/arcnmx/base16-vim/commit/807e442d95c57740dd3610c9f9c07c9aae8e0995).

> Can you give a minimal vimrc to reproduce?

Sorry I missed this, if this is why this was closed I believe it's literally just `set cursorline` - what's unknown here? The PR to fix it was reverted due to unspecified breakage, but the original issue appears to be pretty self-evident:
1. non-gui error highlights are set up as [fg=base00(default background) bg=base08(deleted/red)](https://github.com/fnune/base16-vim/blob/master/templates/default.mustache#L293)
2. `set cursorline` applies [bg=base01(lighter background)](https://github.com/fnune/base16-vim/blob/bbb1af4e00af4df10dd7c492c5c8f1fddacb9908/templates/default.mustache#L234) to the current line

So by design, you get text with a foreground of base00 (black) and a background of base01 (slightly less black) - which isn't really a valid combination of base16 colours. I'm not sure whether vim has a concept of highlighter "priorities", but the issue appears to be that `CursorLine` takes precedence over `ErrorHighlight`. [I found some relevant discussion though, if it helps](https://old.reddit.com/r/vim/comments/ga4xe0/why_use_reverse_for_tui_highlights/). Presumably a few options for a solution are to use `reverse` again as the original PR attempted to do, or to use a foreground colour for `ErrorHighlight` that wouldn't be invalid and unreadable when mixed with other contexts.

**Comment by GordianDziwis** [comment] 2022-01-06 10:44
The breakage comes from, that the template is currently set up in a way that the`reverse` option also applies for gui colors.
If you want to to upstream there are two options:
1. Change the template in a way, that it is possible to set `cterm=reverse` without setting `gui=reverse`
2. Solve the conflict only by setting `ctermfg` and `ctermbg` variables.

**Comment by JamyGolden** [comment] 2023-08-28 08:43
Since there hasn't been any movement here in a while I'm going to close this issue, but we can re-open if something more happens.

**Closed as completed by JamyGolden** 2023-08-28 08:43 UTC
