### ISSUE TITLE
[Bug report] Links in help docs are the same color as regular text.

### ISSUE THREAD

**Issue by andy-gorman** [tinted-theming/tinted-vim#73] opened 2023-12-28 23:36 UTC
## Describe the bug

Links in help docs should be a different color than the typical text, but using base16-shell and base16-vim, that is not the case.

## Expected behavior
Links have a different color than typical text in a help document.

## Screenshots

<img width="728" alt="Screenshot 2023-12-28 at 6 33 04 PM" src="https://github.com/tinted-theming/base16-vim/assets/1248483/d6b49438-e348-4571-b5d0-9a1048e3b278">

In the screenshot above, the text `g0` is a link, and should not appear as regular text.

## **System**

Neovim

**Vim or Neovim version:**
v0.9.4

**Any other plugins you may consider relevant:**

## Minimal configuration file
Bashrc contents
```bash
BASE16_SHELL_PATH="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL_PATH/profile_helper.sh" ] && \
        source "$BASE16_SHELL_PATH/profile_helper.sh"
base16_classic-dark
```

Neovim's init.lua file
```lua
local set_theme_path = "$HOME/.config/tinted-theming/set_theme.lua"
local is_set_theme_file_readable = vim.fn.filereadable(vim.fn.expand(set_theme_path)) == 1 and true or false
if is_set_theme_file_readable then
        vim.cmd("let base16colorspace=256")
        vim.cmd("source" .. set_theme_path)
end
```

## Additional context
I tooled around a bit with regular vim as well and had the same issue.

**Comment by JamyGolden** [comment] 2023-12-29 09:34
Hey @andy-gorman :wave: Hmm, do you have `base16-vim/colors` directory existing at `~/.config/nvim/colors`? I have symlinked `ln -s /path/to/base16-vim/colors ~/.config/nvim/colors`. Just checking since the lua you added to `init.lua` won't do anything unless those files exist there since it's essentially just running `:colorscheme <SCHEME>` in vim.

I've done a quick check and it seems like the links are highlighted on my setup:
![image](https://github.com/tinted-theming/base16-vim/assets/602472/a25f01d6-4ad3-4dd8-a4cc-f4854bb4aeb5)

**Comment by andy-gorman** [comment] 2023-12-29 23:48
Hey @JamyGolden, yes I followed the installation instructions specified here
https://github.com/tinted-theming/base16-vim#manual-neovim

**Comment by JamyGolden** [comment] 2023-12-30 11:01
What theme are you using? I see `base16_classic-dark` is mentioned, but the theme looks different in your screenshot. Does the issue continue to happen while using different themes?

**Comment by andy-gorman** [comment] 2023-12-31 02:39
Ah, you're right, in that screenshot, I'm using nord. The issue does persist across separate themes for me.

**Comment by JamyGolden** [comment] 2024-01-03 13:02
It's strange anyway though, since it seems to work correctly in Nord for me: 
![image](https://github.com/tinted-theming/base16-vim/assets/602472/97fbbd83-6a99-48fc-807b-a8006ba90501)

**Comment by andy-gorman** [comment] 2024-01-03 18:20
Hm. Is there anything else I could provide that would be useful to help identify what's happening? I'm baffled as well by this. I am going to try to poke around with my install this weekend to see if I can debug what's going on.

**Comment by JamyGolden** [comment] 2024-01-04 09:30
@BonaBeavis do you have any ideas about what the cause of this could be?

**Comment by andy-gorman** [comment] 2024-01-16 15:13
Hello! I haven't been able to make any headway here. Am I just out of luck for the time being?

**Comment by JamyGolden** [comment] 2024-01-17 10:36
Hello :) I'd suggest updating all your apps and making sure it's all running the latest versions. I can't replicate this, even with `base16-nord` on nvim on my Linux or Mac machine. Since I'm unable to debug I'll close the issue. If you find a way to replicate it, feel free to open this issue again.

**Closed as completed by JamyGolden** 2024-01-17 10:36 UTC
Labels: bug
